---
title: "p8105_hw5_zv2138"
output: github_document
---

```{r}
library(tidyverse)
```

# Problem 1
```{r}
homicides_df = 
  read_csv("./homicide-data.csv", na = c("", "Unknown")) %>% 
  mutate(
    city_state = str_c(city, state),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved")
    ) %>% 
  relocate(city_state) %>% 
  filter(city_state != "TulsaAL")
```

Let's focus on Baltimore MD 
```{r}
baltimore_df = 
  homicides_df %>% 
  filter(city_state == "BaltimoreMD")

baltimore_summary = baltimore_df %>% 
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )

balimtore_test = 
  prop.test(x = baltimore_summary %>% pull(unsolved), 
          n = baltimore_summary %>% pull(n))

balimtore_test %>% 
  broom::tidy()
```

Let's try to iterate across cities
```{r}
prop_test_function = function(city_df) {

  city_summary = 
    city_df %>% 
    summarize(
      unsolved = sum(resolution == "unsolved"),
      n = n()
    )
  
  city_test = 
    prop.test(x = city_summary %>% pull(unsolved), 
            n = city_summary %>% pull(n))
  
  return(city_test)
}

```

Let's iterate across all cities
```{r}
results_df = 
  homicides_df %>% 
  nest(data = uid:resolution) %>% 
  mutate(
    test_results = map(data, prop_test_function),
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, estimate, starts_with("conf"))
```

Try to make a plot showing estimates and confidence intervals 
```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

```{r}
homicides_df %>% 
  group_by(city_state) %>% 
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  ) %>% 
  mutate(
    test_results = map2(unsolved, n, prop.test), 
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, estimate, starts_with("conf"))

```

# Problem 2
```{r}
research_data = tibble(
  files = list.files("./zip_data/"),
  data = map(str_c("./zip_data/",files), read_csv)
)

tidy_research = 
  research_data %>% 
  unnest(data) %>% 
  mutate(research_arm = ifelse(str_detect(files, "con"), "control arm", "experimental arm")) %>% 
  mutate(subject_id = as.character(as.numeric(substr(files, 5, 6)))) %>% 
  relocate(research_arm, subject_id) %>% 
  select(-files) %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    names_prefix = "week_",
    values_to = "data"
  )

```

# Problem 3
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

```{r}
fill_in_missing = function(x) {
  if(is.numeric(x)){
    ifelse(is.na(x) == T, mean(x, na.rm = T), x)
  }
  else if(is.character(x)){
    ifelse(is.na(x) == T, "virginica", x)
  }
}

iris_complete = map(iris_with_missing, fill_in_missing) %>% 
  as.data.frame()
```

